name: This is an example about how to use var on githubactions

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    env:
      MY_VAR: My env var
    steps:
      - name: Testing
        env:
          STEP_MY_VAR: Hello Juan Esponoza
        run: echo "running actions on branch $github.ref_name, the value of variable is; $MY_VALUE"